site_name: Reloaded III Specification
site_url: https://reloaded-project.github.io/Reloaded-III/

repo_name: Reloaded-Project/Reloaded-III
repo_url: https://github.com/Reloaded-Project/Reloaded-III

edit_uri: edit/main/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sewer56
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheSewer56

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - Custom/Stylesheets/extra.css
  - Reloaded/Stylesheets/extra.css

plugins:
  - search

theme:
  name: material
  palette:
    primary: red
    accent: red
    scheme: reloaded3-slate
  features:
    - navigation.instant
    - content.action.edit

nav:
 - Home: index.md
 - Mod Loader:
   - Backends:
     - About: Loader/Backends/About.md
     - Native: Loader/Backends/Native.md
     - .NET (CoreCLR):
       - About: Loader/Backends/CoreCLR.md
       - Dependency Injection: Loader/Backends/CoreCLR-Dependency-Injection.md
   - Breaking Changes: Loader/Breaking-Changes.md
   - Copy Protection:
       - About: Loader/Copy-Protection/About.md
       - Windows - Denuvo: Loader/Copy-Protection/Windows-Denuvo.md
       - Windows - MS Store: Loader/Copy-Protection/Windows-MSStore.md
       - Windows - SafeDisc: Loader/Copy-Protection/Windows-SafeDisc.md
       - Windows - Steam: Loader/Copy-Protection/Windows-Steam.md
   - Core Architecture: Loader/Core-Architecture.md
   - Dependency Injection: Loader/Dependency-Injection.md
   - Loader Deployment: Loader/Deployment.md
   - Platform Support:
       - About: Loader/Platforms/About.md
       - Linux: Loader/Platforms/Linux.md
       - OSX: Loader/Platforms/OSX.md
       - Other: Loader/Platforms/Other.md
       - Windows: Loader/Platforms/Windows.md
 - Server (Manager Backend):
   - Configurations:
     - App Metadata: Server/Configurations/App-Metadata.md
     - Mod Configuration: Server/Configurations/Mod-Configurations.md
     - Mod Metadata: Server/Configurations/Mod-Metadata.md
   - Diagnostics: Server/Diagnostics.md
   - Load Ordering: Server/Load-Ordering.md
   - Mod Publishing: Server/Mod-Publishing.md
   - Packaging:
     - About: Server/Packaging/About.md
     - Package Metadata: Server/Packaging/Package-Metadata.md
 - Launcher (Manager Frontend):
   - Best Practices: Launcher/Best Practices.md
 - Mods:
   - Essentials:
     - Virtual FileSystem: 
       - About: Mods/Essentials/Virtual-FileSystem/About.md
   - Guidelines:
     - Game Support Mods: Mods/Guidelines/Game-Support.md
     - Middleware Mods: Mods/Guidelines/Middleware.md
 - Online Services:
   - Community Repository: Services/Community-Repository.md
 - FAQ: FAQ.md
 - Research & Explanations:
   - Bootloaders:
     - About: Research/Bootloaders/About.md
     - Linux:
       - Linux - Preload: Research/Bootloaders/Linux-Preload.md
     - macOS:
       - OSX - Preload: Research/Bootloaders/OSX-Preload.md
     - Windows:
       - Windows - DLL Hijack: Research/Bootloaders/Windows-DllHijack.md
       - Windows - Inject Into Suspended Process: Research/Bootloaders/Windows-InjectIntoSuspended.md
 - Wiki:
   - Contributing Locally: Contributing-Locally.md
   - Contributing Online: Contributing-Online.md