site_name: Reloaded III Specification
site_url: https://reloaded-project.github.io/Reloaded-III/

repo_name: Reloaded-Project/Reloaded-III
repo_url: https://github.com/Reloaded-Project/Reloaded-III

edit_uri: edit/main/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sewer56
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheSewer56

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - Custom/Stylesheets/extra.css
  - Reloaded/Stylesheets/extra.css

plugins:
  - search

theme:
  name: material
  palette:
    primary: red
    accent: red
    scheme: reloaded3-slate
  features:
    - navigation.instant
    - content.action.edit

nav:
  - Home: index.md
  - Mod Loader:
      - Loader Design:
          - Core Architecture: Loader/Core-Architecture.md
          - Load Ordering: Loader/Load-Ordering.md
      - Platform Support:
          - About: Loader/Platforms/About.md
          - Windows: Loader/Platforms/Windows.md
          - Switch: Loader/Platforms/Switch.md
          - Linux: Loader/Platforms/Linux.md
          - OSX: Loader/Platforms/OSX.md
      - Bootloaders:
          - About: Loader/Bootloaders/About.md
          - Windows - DLL Hijack: Loader/Bootloaders/Windows-DllHijack.md
          - Windows - Inject Into Suspended Process: Loader/Bootloaders/Windows-InjectIntoSuspended.md
          - Linux - Preload: Loader/Bootloaders/Linux-Preload.md
      - Copy Protection:
          - About: Loader/Copy-Protection/About.md
          - Windows - Steam: Loader/Copy-Protection/Windows-Steam.md
          - Windows - MS Store: Loader/Copy-Protection/Windows-MSStore.md
      - Backends:
          - About: Loader/Backends/About.md
          - Native: Loader/Backends/Native.md
          - .NET (CoreCLR): Loader/Backends/CoreCLR.md
      - Configurations:
          - Mod Metadata: Loader/Configurations/Mod-Metadata.md
          - Mod Configurations: Loader/Configurations/Mod-Configurations.md
      - Mod Configuration: Loader/Mod-Configurations.md
      - Adding Game Support: Loader/Game-Support.md
      - Handling Middleware: Loader/Middleware.md
      - Dependency Injection: Loader/Dependency-Injection.md
      - Mod Publishing: Loader/Build-System.md
      - Loader Deployment: Loader/Deployment.md
        
  - Mod Manager:
      - Configurations:
          - App Metadata: Manager/Configurations/App-Metadata.md
    
  - Online Services:
      - Community Repository: Services/Community-Repository.md
    
  - Backwards Compatibility:
      - About: BackCompat/00_About.md
      - Reloaded II: BackCompat/Reloaded-II.md
      - HedgeModManager: BackCompat/HedgeModManager.md
        
  - FAQ: FAQ.md
  - Best Practices: Best Practices.md
  
  - Wiki: 
    - Contributing Locally: Contributing-Locally.md
    - Contributing Online: Contributing-Online.md